### ISSUE TITLE
trolling done right

### ISSUE THREAD

**Issue by buraktamturk** [souporserious/react-trix#1]
I see nothing but a div :'(

Is it made for trolling purposes or am i having problem with loading trolling.dll into my brain address-space?

https://github.com/souporserious/react-trix/blob/master/src/Trix.jsx

**Comment by souporserious** [comment]
Haha sorry! Been busy and didn't get to it as fast as I would have liked. Thanks for the motivation though :) it's now working https://github.com/souporserious/react-trix/commit/a78104c4dfa99b91ad23ddeac3640bbc667e6ac7 please let me know any issues you find, or suggestions you have. I'll be updating it with things like adding custom toolbars and other stuff in the future.

**Comment by buraktamturk** [comment]
Aww! I didn't meant to write the entire library. Now, I feel so responsible for this :/ 

The fact is I were starting a new *personal* project. But I lost my motivation when the first time I saw this library. ;)

I hope your commit and comment motivates me as well ;) (and I am too busy in these weeks too)

Thanks!

**Comment by souporserious** [comment]
No worries at all :) it was good motivation for me to finally start it!
